import type { Metadata } from "next";
import { Josefin_Slab, Josefin_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";

const playfair_display = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  display: "swap",
});

const josefin_sans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  display: "swap",
});

const josefin_slab = Josefin_Slab({
  subsets: ["latin"],
  variable: "--font-josefin-slab",
  display: "swap",
});

const metadata: Metadata = {
  title: "Corpus Palace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${playfair_display.variable} ${josefin_sans.variable} ${josefin_slab.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
